version: '3.4'

services:
  ui:
    environment: 
      ASPNETCORE_ENVIRONMENT: "Development" 
      ConnectionStrings__DefaultConnection: "Server=db;Database=TripTracker;user=sa;password=TripTracker1234$$;MultipleActiveResultSets=true"   
  backservice:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
  db:
    environment:
      SA_PASSWORD: "TripTracker1234$$"
      ACCEPT_EULA: "Y"